name: dev_utils
description: A collection of reusable Flutter widgets and utilities.
version: 0.0.1
homepage: https://github.com/JonathanGech/flutter_dev_utils.git

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hugeicons: ^0.0.11

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
